### ISSUE TITLE
I'm making a boat nerfing mod with Mixin for 1.15.2. In what file are the Poise boats mod defined?

### ISSUE THREAD

**Issue by Mizhok** [minecraftabnormals/The-Endergetic-Expansion#101]
I'm making a mod that uses mixin injection to nerf boats being super fast over ice. 

Does this mod define a similar class that wouldn't be effected by an injection to BoatEntity, or does your boat extend it?

I tested my mod with yours and it didn't work, so I'm inclined to assume the former. 

Do you know of some work around for this?

**Comment by Mizhok** [comment]
I actually found the file in Abnormals Core. I post it there.

**Comment by SmellyModder** [comment]
Our boats in AC don't override anything to do with faster motion over ice, so mixing into boats will work properly on our boats too.
