### ISSUE TITLE
[1.16.1] Server crashing randomly in the end.

### ISSUE THREAD

**Issue by aking4125** [minecraftabnormals/The-Endergetic-Expansion#108]
Hello!

We're getting this crash on the server randomly when users traverse The End. Any ideas? 
[crash-2020-10-17_23.11.51-server.txt](https://github.com/minecraftabnormals/The-Endergetic-Expansion/files/5397020/crash-2020-10-17_23.11.51-server.txt)

**Comment by hannesa2** [comment]
You run into this lint warning

<img width="767" alt="image" src="https://user-images.githubusercontent.com/3314607/96359558-78e19580-1114-11eb-9b71-2ea9e3bc11ea.png">

**Comment by bageldotjpg** [comment]
This was already fixed in 2.1.1, update to fix it;
https://www.curseforge.com/minecraft/mc-mods/endergetic/files/3075871

**Comment by hannesa2** [comment]
Curious, how does `2.1.1 `fix it ?
On current latest commit 6c40c46dac3a1b5 on branch `1.16.x` there is still this possible `NullPointerException` issue.

Can you point me to the fix/commit in `2.1.1` which should solved it ?

**Comment by bageldotjpg** [comment]
https://github.com/minecraftabnormals/The-Endergetic-Expansion/commit/871df49d884851bf0bbc9b63924f9d7873df8a4b
