### ISSUE TITLE
Please add "hacktoberfest" topic to your repo

### ISSUE THREAD

**Issue by hannesa2** [minecraftabnormals/The-Endergetic-Expansion#112]
It would be nice, if you put a `hacktoberfest` topic to your repo like this

![image](https://user-images.githubusercontent.com/3314607/96359970-c3651100-1118-11eb-81bc-e12e34659160.png)

Here you have more details https://hacktoberfest.digitalocean.com/

**Comment by SmellyModder** [comment]
Why???
