### ISSUE TITLE
Endergetic 4.0.0 Beta 1 Incompatible with Structure Gel

### ISSUE THREAD

**Issue by Kuusotare** [minecraftabnormals/The-Endergetic-Expansion#221]
Minecraft 1.19.2, Forge 43.1.25

Attempting to run the game with only Blueprint, Endergetic, and Structure Gel installed crashes the game on startup. Removing Structure Gel or Endergetic fixes the issue.

**Comment by ihaveacrushonjaidenanimations2068** [comment]
i think endergetic is incompatible with 1.19.2 itself

**Comment by SmellyModder** [comment]
Send the crash report. Endergetic is not even ready for 1.19.2 yet.

**Comment by murao-kun** [comment]
I ported the mod to 1.19.2 to test this issue, and seems like they are working just fine.
This one should be closed. 
Author just used 1.19 version in 1.19.2, that should not work as intended.

**Comment by ddship12** [comment]
Endergetic 4.0.0 Beta 1, Can i download the beta mod?
