### ISSUE TITLE
Recipe Errors

### ISSUE THREAD

**Issue by WenXin20** [minecraftabnormals/The-Endergetic-Expansion#23]
`Minecraft v1.14.4`
`Endergetic Expansion v1.1.2`

- The first recipe error is for `endergetic:poise_slab_from_vertical`, the logs says it's because the output has a `/` in the id.
- Same for the `endergetic:eumus_brick_slab_from_vertical`, it has a `/` in the output.

**Comment by SmellyModder** [comment]
Do you have Quark installed

**Comment by WenXin20** [comment]
Yes

**Comment by WenXin20** [comment]
But the error is because the output is incorrectly defined. I checked the recipe file for it, and it says the output is `/endergetic:poise_slab`. Same for the other one.

**Comment by SmellyModder** [comment]
Will fix 👍
