### ISSUE TITLE
boof blocks can't be mined fast with Farmer's delight knives

### ISSUE THREAD

**Issue by thelegitdolt** [minecraftabnormals/The-Endergetic-Expansion#231]

**Comment by SmellyModder** [comment]
Elaborate.

**Comment by thelegitdolt** [comment]
usually FD knives had automatic support for things it mined fast, which included leathery thing like bedrolls back in 1.16.5, and i think boof blocks too, but they changed it after mineable stuff came out

**Comment by thelegitdolt** [comment]
either way i think boof blocks are pretty leathery, so it would make sense imo imo

**Comment by SmellyModder** [comment]
It looks like Farmer's Delight has a tag for it. I'll add support for this soon.

**Comment by thelegitdolt** [comment]
aweosme sauce
