### ISSUE TITLE
Wall ender torches produce wrong particles

### ISSUE THREAD

**Issue by Firch** [minecraftabnormals/The-Endergetic-Expansion#251]
![изображение](https://github.com/team-abnormals/endergetic/assets/47253246/61dd6fea-6a23-4618-b4e0-23c1c8be8c6e)

Happens with wall-mounted torches.

Expected behavior: Ender flame particles instead of regular flame

Endergetic version: endergetic-1.19.2-4.0.0

**Comment by bageldotjpg** [comment]
Fixed indev
