### ISSUE TITLE
Return end gateway is consist of bedrock instead of mystical obsidian

### ISSUE THREAD

**Issue by GoldenTotem** [minecraftabnormals/The-Endergetic-Expansion#255]
Minecraft 1.16.5  Forge 36.2.35  Endergetic 3.0.2

Return end gateway remain the vanilla style, which means they are consist of bedrock.

Return end gateway means gateways that randomly generated throughout the outer islands, not spawned around the central island after each death of the ender dragon.

**Comment by bageldotjpg** [comment]
1.16.5 is no longer supported, re-open if issue persists on 1.19.2.
