### ISSUE TITLE
Ctd on startup

### ISSUE THREAD

**Issue by Roonas** [minecraftabnormals/The-Endergetic-Expansion#26]
[Null pointer exception for a missing registry object is thrown on boot.](https://pastebin.com/G8m0jwPM)

EE: 1.15.2-v1.2.5
Forge: 31.1.0

**Comment by SmellyModder** [comment]
Try using the latest forge. This is a known bug and appears to be caused by external things, not the mod itself, it's a problem with forge atm.

**Comment by Roonas** [comment]
Updated to Forge 31.1.24 and that fixes the issue.
