### ISSUE TITLE
Bolooms strings are invisible when using Iris shaders mod

### ISSUE THREAD

**Issue by Yokohama76** [minecraftabnormals/The-Endergetic-Expansion#260]
Bolooms strings are invisible when using Iris shaders mod.
![2024-06-22_19-08-16-min](https://github.com/team-abnormals/endergetic/assets/173561120/e6ca0238-7a39-448c-b1c0-eb9521b19000)
![2024-06-22_19-07-28-min](https://github.com/team-abnormals/endergetic/assets/173561120/cc0f1c60-a862-4e7e-af6a-6d28e1105682)

**Comment by SmellyModder** [comment]
To my understanding, this issue is not fixable on our side without losing some of the special visual effects.
