### ISSUE TITLE
First 1.14.4/1.15 Release Build - Poise Forest

### ISSUE THREAD

**Issue by SmellyModder** [minecraftabnormals/The-Endergetic-Expansion#3]
* ~~Finish Poise Forest Generation~~
* ~~Puff Bug~~
* ~~Puff Bug Hives~~
* ~~Booflo(~~Baby~~, ~~Adolescent~~, ~~Adult~~)~~

**Comment by MoriyaShiine** [comment]
How do the remaining 3 features work? I'm interested in helping with the code.

**Comment by SmellyModder** [comment]
They're quite complicated. We're hoping to get more coders as of know to fill in for me; I've been busy with Upgrade Aquatic. If you wish to discuss more, please send me a message on discord at Smelly²#3450. @MoriyaShiine

**Comment by SmellyModder** [comment]
Also if you're wondering what should be done first. It would be Puff Bugs. Booflos are about 2/3 of the way done and the hives go along with Puff Bugs.

**Comment by SmellyModder** [comment]
Release Build coming soon. Puff Bugs are done now. We're just running some tests still and we hope to get ambiance sounds for the Poise Forest before releasing.

**Comment by SmellyModder** [comment]
And then expect a 1.15 port after
