### ISSUE TITLE
Breeding the booflo doesn't give the player The Parrots and the Bats advancement

### ISSUE THREAD

**Issue by Block-Vader** [minecraftabnormals/The-Endergetic-Expansion#31]
You are supposed to get that advancement by breeding any two animals. It seems to works with other modded animals (like snails from autumnity of foxhounds from quark) but not with the booflo.

**Comment by SmellyModder** [comment]
Known, and won't fix. Booflos are not considered animals in the code since they have lots of unique data to them, and to conserve data usage they were split up into multiple entities. I won't go into the full details, but this won't be fixed, it's intentional.

**Comment by Block-Vader** [comment]
Wow, I had no idea it was possible to breed puff bugs. Thanks for reply.
