### ISSUE TITLE
Add compatibility for Corail's Woodcutter

### ISSUE THREAD

**Issue by Insane96** [minecraftabnormals/The-Endergetic-Expansion#38]
So we can use planks into the woodcutter

**Comment by SmellyModder** [comment]
Same response from UA - It appears we cannot, as it is hardcoded in that mod: https://github.com/Corail31/woodcutter/blob/master/src/main/java/ovh/corail/woodcutter/compatibility/SupportMods.java

If you still wish to have this contact the Corail's Woodcutter Mod.

**Comment by Insane96** [comment]
Actually you can by adding the recipes to data/recipes/woodcutting
https://github.com/Corail31/woodcutter/tree/master/src/main/resources/data/corail_woodcutter/recipes/woodcutting
