### ISSUE TITLE
Sound for equipping a booflo vest resuses leather armor equipping sound event, leading to unintuitive subtitles

### ISSUE THREAD

**Issue by muzikbike** [minecraftabnormals/The-Endergetic-Expansion#40]
It's not leather, so this makes no sense.

A unique sound event should be added instead, referring to the same vanilla sound files but with a unique subtitle.

![2020-04-23_11 17 35](https://user-images.githubusercontent.com/52297970/80088413-636c2400-8554-11ea-8c52-ade904a1fb61.png)
![2020-04-23_11 19 33](https://user-images.githubusercontent.com/52297970/80088420-6535e780-8554-11ea-9118-8d267c4efadc.png)

**Comment by SmellyModder** [comment]
The equipping sounds for the Boofloo Vest are just placeholders, it'll be changed to a custom sound eventually.
