### ISSUE TITLE
Encountered Error During Load_Registries Event Phase

### ISSUE THREAD

**Issue by Gemios26** [minecraftabnormals/The-Endergetic-Expansion#47]
Hello! My issue is that when I try to launch this modpack I created, it says:
"The Endergetic Expansion (energetic) encountered an error during the load registries event phase."

I assume you all who read this will need the log, so here you go.

[latest.log](https://github.com/minecraftabnormals/The-Endergetic-Expansion/files/4554365/latest.log)

I hope you guys can help soon, because I am trying to do a server with my friends. Thank you!

**Comment by SmellyModder** [comment]
Try updating your forge

**Comment by Gemios26** [comment]
This made it work, thank you!
