### ISSUE TITLE
Generating features with Corrock Block in modded dimensions causes a crash

### ISSUE THREAD

**Issue by TelepathicGrunt** [minecraftabnormals/The-Endergetic-Expansion#48]
Hello! One person was using The Endergetic Expansion with World Blender which will take Endergetic's features and spawn it in World Blender's own dimension. However, due to the CONVERSIONS map of dimension to blocks for a check, this conversion map will cause a crash when it is given a modded dimensiontype for `CONVERSIONS.get(world.getDimension().getType()).get()` because it is calling .get() on null.  A solution is to do a CONVERSIONS.contains check beforehand as that would solve the crash. 

<https://github.com/minecraftabnormals/The-Endergetic-Expansion/blob/296c8d078b36835d68f9af5d954ac1c47e2d6cdb/src/main/java/endergeticexpansion/common/blocks/BlockCorrockBlock.java#L31>

Crashlog: https://pastebin.com/028fPbQP

I hope this helps! Let me know if you need more info.

Edit: it also seems like this crash will also happen when the block is placed and ticked in a modded dimension as well. If there are any other blocks with conversion maps like this, they all will need the same fix

**Comment by SmellyModder** [comment]
Thanks for reporting.

The Corrock Features aren't supposed to generate yet, they're unobtainable outside of creative normally.

Anyways, this is still an issue. I'm busy with some other stuff and will get around to fixing it, but I'm pretty busy atm, if you want to make PR to fix it that'd be appreciated.
