### ISSUE TITLE
Bollon Balloons don't appear to work on players, mobs or vehicles

### ISSUE THREAD

**Issue by SpiderKolo** [minecraftabnormals/The-Endergetic-Expansion#53]
I right clicked them when holding them and looking in air, checked few mobs and boats...
From my testings it seems that I can only connect them to a fence. And they look and work as intended there.

I checked all variants. None of them works.
I also checked both Creative and Survival. Didn't made a difference.

**Comment by SmellyModder** [comment]
Intentional, that feature hasn't been added yet.

**Comment by SpiderKolo** [comment]
Oh... that explains everything...
Okay, sorry to bother.
