### ISSUE TITLE
Server crash with new forge version

### ISSUE THREAD

**Issue by Darkfiend009** [minecraftabnormals/The-Endergetic-Expansion#56]
Forge: 31.2.0
Minecraft: 1.15.2
Endergetic Expansion: 1.3.0

Crash Report: https://pastebin.com/Q2swESM6

Server crashes while trying to start up with the newest recommended version of Forge (31.2.0).

**Comment by SmellyModder** [comment]
Does it crash on the forge version before 31.2.0?

**Comment by SmellyModder** [comment]
Also, does it crash outside a server?

**Comment by Darkfiend009** [comment]
No and no. 

Although i may have figured out something that was conflicting. I had added the mod Jade to the modpack. I decided to remove it and it appears to be working. So at least that was identified.

Sorry for the bad report though.

**Comment by SmellyModder** [comment]
Ah ok, all good.
