### ISSUE TITLE
No Dragon Egg is spawning when killing the dragon

### ISSUE THREAD

**Issue by Shorepion** [minecraftabnormals/The-Endergetic-Expansion#59]
**Mod version:**
1.3.1

**Description of the issue:**
After killing the Ender Dragon there is no Dragon Egg spawning on the middle Pillar of the portal.
I used 4x normal End Crystals to reactivate the Dragon fight.
Here is a short video of the fight, you can skip to the end when I defeated the Ender Dragon (rejoining the world and block update of the pillar didnt work as you can see in the video):
[https://youtu.be/S2RFoWEGqtY](https://youtu.be/S2RFoWEGqtY)

**Modpack and current Modlist:**
[https://www.curseforge.com/minecraft/modpacks/magica-infinitum-ii](https://www.curseforge.com/minecraft/modpacks/magica-infinitum-ii)

**Comment by SmellyModder** [comment]
All those links are leading back to the issues page for me.

> I used 4x normal End Crystals to reactivate the Dragon fight.
There's your problem, you're resummoning the dragon, inferring it's already been killed. Dragon Eggs only get spawned once.

**Comment by Shorepion** [comment]
> All those links are leading back to the issues page for me.
Fixed that.

> There's your problem, you're resummoning the dragon, inferring it's already been killed. Dragon Eggs only get spawned once.
Ok, sorry didnt know this was changed in vanilla 1.15.2.
Its all fine then I guess. Thanks for the quick response!

**Comment by SmellyModder** [comment]
No problem!
