### ISSUE TITLE
[1.15.2] SMP Startup Crash - common_setup event phase 

### ISSUE THREAD

**Issue by mr-poyo** [minecraftabnormals/The-Endergetic-Expansion#65]
**Forge Version:** 31.2.0
**Mod Version:** The-Endergetic-Expansion-1.15.2-v1.3.1.jar

Hello,

I am not entirely sure if this is something on my end or the mod's end, but I am working on a custom modpack and I occasionally get the following crash on my server during Startup. It happens on SMP startup, only sometimes (15% of the time? Not exactly sure), and requires me to reboot the server. 

Crash report: https://pastebin.com/UdewBWR7
Latest.Log: https://pastebin.com/7eBiws5T

Any ideas on what could be going on? Thank you!

**Comment by SmellyModder** [comment]
The crash doesn't give many details on what's specifically causing it.

**Comment by SmellyModder** [comment]
My guess is it's some sort of mod conflict.

**Comment by SmellyModder** [comment]
I believe this is caused by some threaded desync issues, which have recently been fixed in dev.
