### ISSUE TITLE
Boof Block Crash

### ISSUE THREAD

**Issue by ChrisLTheNerd** [minecraftabnormals/The-Endergetic-Expansion#71]
Everytime I shoot a bloof block with a bow and arrow it crashes me.

![ezgif com-video-to-gif (9)](https://user-images.githubusercontent.com/50182206/86521212-b1868900-be1b-11ea-8cd9-4fbc9b5f0fdf.gif)

This is the crash report
[crash-2020-07-04_17.28.45-server.txt](https://github.com/minecraftabnormals/The-Endergetic-Expansion/files/4873927/crash-2020-07-04_17.28.45-server.txt)

**Comment by TheWitherlord** [comment]
same crash here too.

**Comment by SmellyModder** [comment]
This was fixed in the 1.16 port of the mod. 
Unfortunately, Abnormal Mods will no longer be releasing new 1.15 versions of its mods.
If you still want to have this issue fixed you can go back to version `1.3.1` of the mod.
