### ISSUE TITLE
puffbug hive

### ISSUE THREAD

**Issue by ShinyRayquaza9923** [minecraftabnormals/The-Endergetic-Expansion#72]
I came from the wiki page because there was nothing there about puffbug hive.
I wanted to harvest/mine/take the hive to bring it to overworld. I tried silk touch axe and shears but none of them dropped anything.
Is it actually possible to mine it? If yes, what do I use?

**Comment by SmellyModder** [comment]
In the currently released versions, you can't mine Puff Bug Hives and have it drop the item. You can give a pollinated(levitating) Puff Bug a Bolloom Fruit to make it produce a hive item.
