### ISSUE TITLE
1.15.2-1.3.2 Loading Failed Exception

### ISSUE THREAD

**Issue by kreezxil** [minecraftabnormals/The-Endergetic-Expansion#73]
Issue:  1.15.2-1.3.2 crashes dedicated server Forge 1.15.2 build 31.2.31

Notes:
     LoadingFailedException

crash report: 
http://paste.ubuntu.com/p/jgFRGjXWvx/

fml server latest: 
http://paste.ubuntu.com/p/j3pSjVdD3W/

**Comment by SmellyModder** [comment]
You're running `The-Endergetic-Expansion-1.14.4-v1.2.0` not `The-Endergetic-Expansion-1.15.2-v1.3.2`.
