### ISSUE TITLE
Server Disconnect on Loading New Biomes

### ISSUE THREAD

**Issue by Rileybutt** [minecraftabnormals/The-Endergetic-Expansion#79]
I'm not sure if this problem is Endergetic Expansion directly but I'm running a private server with friends and whenever any of us load (or reload after leaving the End) any of the new biomes added we get disconnected from the server.

If we try to rejoin, we either can get in before the chunks load (though as soon as we near the new biome's chunks we DC again.) or we get stuck in a loop of being disconnected then rejoining only to instantly disconnect again.

This is the message everyone gets every time they're disconnected:
![UeCfBGB](https://user-images.githubusercontent.com/36881548/88614010-ce9a2a80-d05c-11ea-8c21-840428d5af93.png)

The only differing aspect of this are the numbers are sometimes different between players or between disconnects alone.

One last thing is sometimes, for some players (not all) after restarting the server the game allows them to reconnect and even explore the biomes entirely.

Like I said, I have no idea if its EE alone or if something else is causing it. I've just noticed it happens everytime we load EE's biomes like Poise Forest. Is there a way to fix this or do you know at least what would be causing this if not EE? I could really use the help as I don't want to have to remove EE from my game.

**Comment by SmellyModder** [comment]
I'm not sure what the issue is since there's no log of what's going on. 
There should be an error logged on the server when the player gets disconnected.

**Comment by Rileybutt** [comment]
Yeah, sorry.
Here's the log when it happened to me earlier. This is from as soon as I disconnected and then I tried reconnecting a few times only to dc immediately like I said above.

[https://pastebin.com/9Bzu9s9A](url)

**Comment by SmellyModder** [comment]
Hmm, it's still fairly unclear what the cause of the disconnection is. 
It's still fairly unclear because the logs don't really state any internal error on the server, which makes it likely client-related, so send the client log for when you got disconnected.
But it seems after you join the server it starts running slower, which might explain why it disconnects you.

**Comment by Rileybutt** [comment]
Here's my client log from when I first entered the end to the repeated disconnects and reconnects. I'm not sure where each dc/reconnect starts and ends so I grabbed a few of the repeating sections to make sure I got everything from during the issue.

[https://pastebin.com/DCb7M9jD](url)

**Comment by SmellyModder** [comment]
Hmm, there still aren't many details of why you got disconnected. I'm unable to reproduce this, but if I am I'll make sure to re-open this issue.
