### ISSUE TITLE
When creepers explode with balloons on them, potion particles appear as if the creeper blew up with an effect

### ISSUE THREAD

**Issue by WitheredWasabi** [minecraftabnormals/The-Endergetic-Expansion#81]

**Comment by SmellyModder** [comment]
This is due to the balloons using levitation to, well, levitate the mobs they're attached to.

**Comment by WitheredWasabi** [comment]
ah, i see. The levitation causes other wacky things also. Like you could complete advancements that require having the levitation effect such as Great View up Here and How Did We Get Here.

**Comment by SmellyModder** [comment]
Also known. Minecraft has levitation (or constant motion upwards) hardcoded so I just decided to use Levitation. I'm considering adding a hook for the balloons and not making it use levitation, but the hardcoding is deep-rooted in some if statements.
