### ISSUE TITLE
[Suggestion] downgrade to 1.12.2 please read in full.

### ISSUE THREAD

**Issue by PercyJames** [minecraftabnormals/The-Endergetic-Expansion#82]
**now, before you close the issue immediately i just want to say these few things.**

1: 1.12.2 is currently the most popular modding version.

2: i know the code is different and it would make no sense to do so.

3: there are basically no end expansions for minecraft 1.12.2 that add biomes.

4: it doesn't even have to be multiple releases of a 1.12.2 version and the textures don't have to be redone. you could just release one version of the mod for 1.12.2 and be done with it forever.

i know this is a dumb request but i just need to get the words out to the people who can make the change. if you won't or can't no hard feelings.

**Comment by bageldotjpg** [comment]
1) Forge no longer supports 1.12, we don't either.
2) This is correct
3) Unfortunate
4) No because that takes time and effort 

Please do not ask us (or other modders) to backport. If they plan to, they plan to. Asking for a port will rarely do anything. Forge no longer supports 1.12 anyway and we try to stay vanilla+ so it makes more sense to stick with Vanilla's versions. If anything you should be encouraging (respectfully so) other modders to move upwards torwards 1.16 and forward.

**Comment by PercyJames** [comment]
understood. however i do have a question. in what way does forge not support 1.12.2? unless i downloaded from the wrong website they still appear to be making updates to the 1.12.2 the most recent being 14.23.5.2854 created at 04/12/20 05:59 PM or do you mean curseforge the mod downloading website? cause in that case i need context as to how that works as many mods such as the auroran is still being updated for 1.2.2 and only 1.12.2.

**Comment by bageldotjpg** [comment]
Forge is no longer updating 1.12, and if mod developers try to get help coding for 1.12 they will turn them down.
If you look at the Forge website, the last 3 were April 2020 (which was 4 months ago) and everything else before that was in 2019.

**Comment by PercyJames** [comment]
i understand the basic concept now. thank you! however i still don't understand why people hesitate to update to 1.16+ but, that's for an issue outside of this mod.

**Comment by Storm-Cloud** [comment]
> Forge is no longer updating 1.12, and if mod developers try to get help coding for 1.12 they will turn them down.
> If you look at the Forge website, the last 3 were April 2020 (which was 4 months ago) and everything else before that was in 2019.
Yeah, the forge team is actually _really rude_ about it too if you ask about 1.12 or 1.13 :/
I appreciate the response you gave to this.
