### ISSUE TITLE
1.15.2 Missing Ogg file

### ISSUE THREAD

**Issue by Yourname942** [minecraftabnormals/The-Endergetic-Expansion#85]
There seems to be a missing sound file in 1.15.2.
Latest log: https://gist.github.com/Yourname942/36fcf68e2c454fcdef0fa88ddfefa2f2

Minecraft 1.15.2
Forge 31.2.36
Abnormals Core 1.0.6
The Endergetic Expansion 1.3.2

**Comment by SmellyModder** [comment]
1.15.2 Endergetic will no longer be receiving updates, unfortunately, but this issue persisted in 1.16 and has now been fixed.
