### ISSUE TITLE
The Exit portal refuses to generate on a server.

### ISSUE THREAD

**Issue by STOKESTER** [minecraftabnormals/The-Endergetic-Expansion#86]
So recently out of no where we had the ender dragon stop spawning when players were placing crystals around the portal. 

I thought a good way to fix this would be to stop the server, delete the end dimension and let it regenerate. I was wrong. The end pillars generated with the crystals on top but the exit portal with mystical obsidian and lanterns etc didn't generate. And the ender dragon didn't spawn. 
![2020-08-15_03 58 18](https://user-images.githubusercontent.com/36657224/90468680-5fdf5700-e15a-11ea-8ee7-1e5b90b34023.png)
 

My next idea was to try generating the end in single player and copying it to the server, this copied the exit portal but the dragon didn't spawn. And afaik you cant place crystals down to spawn the dragon until the runes around the portal are "activated" and glowing pink. I turned on debugging and checked the log, when the portal was copied from singleplayer the log said it found the portal but nothing else about spawning the ender dragon etc.

**Comment by SmellyModder** [comment]
When you delete the end's chunks, but not its dragon data then errors can occur. Try enabling Endergetic's debugger for the portal in the config, it'll tell you where it found a portal if one exists.

**Comment by STOKESTER** [comment]
Hi Smelly, I already had the debugger enabled and the debug.log was filled with found portal at x y z. But the dragon still never spawned, and the 4 runes around the portal weren't in an "active" state. I ended up fixing it by completely rebuilding the portal manually and then placing 4 end crystals. The portal then got lifted up by 1 block and re-generated new end crystal pillars. It's been working again since so I'll close this issue, but could you tell me where the ender dragon can be found in the server files in case this happens again?

**Comment by SmellyModder** [comment]
Well good to hear it's working fine now. 
I programmed it to search for a new portal that players would build to fix this issue in-game if it occurs, which is why it fixed itself when you re-built it.
I don't remember exactly where the dragon data is, but it can be found with an NBT Explorer in the End Dimension's world data.

**Comment by STOKESTER** [comment]
Too easy :) thankyou!
