### ISSUE TITLE
Update the whole mod from 1.16.1 to 1.62 and/or 1.16.3

### ISSUE THREAD

**Issue by TheGoldenCreeper** [minecraftabnormals/The-Endergetic-Expansion#88]
As I am waiting to update mods without breaking my saves, please update the entire mod from Forge 32 to forge 33 and/or 34 for minecraft 1.16.2 or 1.16.3.

**Comment by bageldotjpg** [comment]
The mod will update to 1.16.3 when we are ready to update it. Forge is not in a stable condition worldgen wise for us to port viably yet.
