### ISSUE TITLE
Deadlock when bouncing on Boof Blocks inside a boat

### ISSUE THREAD

**Issue by naiski** [minecraftabnormals/The-Endergetic-Expansion#90]
After a few times bouncing on a boof block while inside a boat a deadlock seems to occur, preventing the game from ticking.  I suspect this may occur with other vehicle entities such as minecarts as well.

**Comment by SmellyModder** [comment]
1.15 versions of Endergetic won't be receiving any new updates, but I can confirm this issue still occurs on 1.16.x

**Comment by naiski** [comment]
> 1.15 versions of Endergetic won't be receiving any new updates, but I can confirm this issue still occurs on 1.16.x

Okay.  I can probably backport the fix for myself once you guys fix it.
