### ISSUE TITLE
How to verify, if installed The-Endergetic-Expansion is installed ?

### ISSUE THREAD

**Issue by VincentZocker** [minecraftabnormals/The-Endergetic-Expansion#98]
First of all: Thank you for the mod with code.

I do my first step with own compile mods and I successfully compiled the mod and installed it to my MultiMC instance

![image](https://user-images.githubusercontent.com/60041276/94995513-25f9d100-059f-11eb-8733-e1784c77099f.png)

But how to verify, if installation was really successful ? Actually I don't find any new item.
Please can you give me a hint ?

![image](https://user-images.githubusercontent.com/60041276/94995565-783af200-059f-11eb-9efe-80f484dce49c.png)

**Comment by SmellyModder** [comment]
Forge tells you what mods are installed, just check for Endergetic.
