### ISSUE TITLE
How to verify, if installed The-Endergetic-Expansion is installed ? #2

### ISSUE THREAD

**Issue by VincentZocker** [minecraftabnormals/The-Endergetic-Expansion#99]
As followup of very fast closed #98 

> just check for Endergetic.

Where to check for `Endergetic` I expected to find it here.
Sorry for the probably stupid question, but I'm new to Minecraft

![image](https://user-images.githubusercontent.com/60041276/94995761-be448580-05a0-11eb-9667-cca21bb8ec17.png)

Maybe you can share a screenshot, this mostly explains a lot without words

**Comment by VincentZocker** [comment]
Now I use output `./build/libs/The-Endergetic-Expansion-1.16.1-2.0.1.jar`

But still now new item with name  `Endergetic*`

![image](https://user-images.githubusercontent.com/60041276/95000368-79304b80-05c0-11eb-9824-b3e06af3cbe2.png)

What's the right way to deploy ?

**Comment by SmellyModder** [comment]
Go to your mods section:
![image](https://user-images.githubusercontent.com/41268323/95003917-99f1a480-05b2-11eb-9701-51bb0d11edd3.png)
Look for Endergetic:
![image](https://user-images.githubusercontent.com/41268323/95003912-7b8ba900-05b2-11eb-90b9-b149b88176f1.png)

**Comment by hannesa2** [comment]
Ahhhh ! Thank you ! Now I understand.

The README.ms is just a thumb template, and to start I've to

- open Intellij and import project
- generate start commands 
<img width="233" alt="image" src="https://user-images.githubusercontent.com/3314607/95013648-fb148900-0641-11eb-93e3-dd3059adf755.png">
- run it 
<img width="192" alt="image" src="https://user-images.githubusercontent.com/3314607/95013654-0798e180-0642-11eb-8cbe-8771c1950597.png">

Sorry for the beginner question, do I need the server as well to run it properly ?
What's the purpose of `runData` ? 
<img width="173" alt="image" src="https://user-images.githubusercontent.com/3314607/95013695-3d3dca80-0642-11eb-9d0c-3b55a3609f88.png">

**Comment by SmellyModder** [comment]
`runServer` is for running the mod on a dedicated server.
`runData` is for generating data, such a blockstates, loot tables, etc.
